spring:
  datasource:
    url: jdbc:h2:mem:appdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  profiles:
    active: h2
  h2:
    console:
      enabled: true
      path: /h2

jwt:
  secret: sj_jwt_secret_key_1234567890_ABCDEFGHIJKLMNOPQRSTUVWXYZ
  expiration-seconds: 3600

---

spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/appdb
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  secret: sj_jwt_secret_key_1234567890_ABCDEFGHIJKLMNOPQRSTUVWXYZ
  expiration-seconds: 3600

springdoc:
  paths-to-match: /api/**
