### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "admin@local",
  "password": "Admin#123"
}

### Get Users
GET http://localhost:8080/api/users?page=0&size=10
Authorization: Bearer {{token}}
